# Generated by Django 6.0.5 on 2026-05-25 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(help_text='e.g. Diesel Combustion, Electricity, Flight', max_length=100)),
                ('scope', models.IntegerField(choices=[(1, 'Scope 1 — Direct Emissions'), (2, 'Scope 2 — Purchased Electricity'), (3, 'Scope 3 — Indirect (Travel/Procurement)')])),
                ('category', models.CharField(choices=[('stationary_combustion', 'Stationary Combustion'), ('mobile_combustion', 'Mobile Combustion'), ('purchased_electricity', 'Purchased Electricity'), ('business_travel', 'Business Travel'), ('employee_commuting', 'Employee Commuting'), ('procurement', 'Procurement'), ('other', 'Other')], max_length=50)),
                ('quantity', models.FloatField(help_text='Original quantity from source')),
                ('original_unit', models.CharField(help_text='Unit as reported in source', max_length=50)),
                ('normalized_quantity', models.FloatField(help_text='Quantity after unit normalization')),
                ('normalized_unit', models.CharField(help_text='Standard unit after normalization', max_length=50)),
                ('emission_factor_value', models.FloatField(blank=True, help_text='Snapshot of factor used', null=True)),
                ('co2e_kg', models.FloatField(blank=True, help_text='Calculated CO2 equivalent in kg', null=True)),
                ('activity_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('plant_code', models.CharField(blank=True, default='', max_length=20)),
                ('facility', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('validated', 'Validated'), ('flagged', 'Flagged for Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('locked', 'Locked for Audit')], default='pending', max_length=20)),
                ('suspicious', models.BooleanField(default=False)),
                ('suspicious_reasons', models.JSONField(blank=True, default=list, help_text='List of validation flags')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewer_comment', models.TextField(blank=True, default='')),
                ('locked', models.BooleanField(default=False)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'activity_records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(help_text='e.g. diesel_combustion, electricity, flight', max_length=100)),
                ('fuel_type', models.CharField(blank=True, default='', help_text='e.g. diesel, coal, natural_gas', max_length=100)),
                ('unit', models.CharField(help_text='Input unit e.g. liters, kWh, km', max_length=50)),
                ('factor_value', models.FloatField(help_text='kg CO2e per unit')),
                ('factor_unit', models.CharField(default='kg_co2e', help_text='Output unit', max_length=50)),
                ('source', models.CharField(help_text='e.g. DEFRA 2025, EPA GHG Hub', max_length=255)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'emission_factors',
                'ordering': ['activity_type', 'fuel_type'],
            },
        ),
    ]
