# Generated by Django 6.0.5 on 2026-05-25 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField(help_text='Row number in the source file (1-indexed)')),
                ('raw_payload', models.JSONField(help_text='Exact JSON representation of the source row')),
                ('ingestion_status', models.CharField(choices=[('pending', 'Pending'), ('parsed', 'Parsed'), ('normalized', 'Normalized'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'raw_records',
                'ordering': ['datasource', 'row_number'],
            },
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('sap', 'SAP Fuel & Procurement'), ('utility', 'Utility Electricity'), ('travel', 'Travel & Expenses')], max_length=20)),
                ('ingestion_method', models.CharField(choices=[('csv', 'CSV Upload'), ('api', 'API Integration'), ('manual', 'Manual Entry')], default='csv', max_length=20)),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('uploading', 'Uploading'), ('parsing', 'Parsing'), ('normalizing', 'Normalizing'), ('completed', 'Completed'), ('failed', 'Failed'), ('partial', 'Partially Completed')], default='uploading', max_length=20)),
                ('total_rows', models.IntegerField(default=0)),
                ('processed_rows', models.IntegerField(default=0)),
                ('failed_rows', models.IntegerField(default=0)),
                ('error_summary', models.TextField(blank=True, default='')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_sources', to='organizations.organization')),
            ],
            options={
                'db_table': 'data_sources',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
