# Generated by Django 6.0.5 on 2026-05-25 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirportLookup',
            fields=[
                ('iata_code', models.CharField(max_length=3, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
            options={
                'db_table': 'airport_lookup',
                'ordering': ['iata_code'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('industry', models.CharField(choices=[('manufacturing', 'Manufacturing'), ('energy', 'Energy & Utilities'), ('logistics', 'Logistics & Transportation'), ('technology', 'Technology'), ('finance', 'Financial Services'), ('healthcare', 'Healthcare'), ('retail', 'Retail'), ('construction', 'Construction'), ('other', 'Other')], default='manufacturing', max_length=50)),
                ('country', models.CharField(default='India', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'organizations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='SAP plant code e.g. 1102', max_length=20)),
                ('name', models.CharField(help_text='e.g. Berlin Manufacturing Plant', max_length=255)),
                ('location', models.CharField(help_text='City/region', max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='organizations.organization')),
            ],
            options={
                'db_table': 'plants',
                'ordering': ['code'],
                'unique_together': {('organization', 'code')},
            },
        ),
    ]
